services:
  app:
    build: .
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Correct path inside the container
    ports:
      - "80:80"
    depends_on:
      - app
