services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/fastapi.talut.tech/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/fastapi.talut.tech/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - web
