name: CI - Run Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest

    - name: Test Docker Build
      run: |
        docker build -t fastapi-app .
        docker run -d --name test-container -p 8000:8000 fastapi-app
        sleep 5
        curl http://localhost:8000/api/v1/books
